### ISSUE TITLE
[Possible Bug] Spec file path not getting cached when using <test> ?

### ISSUE THREAD

**Issue by VlatkoGoljevacki** [AlexB52/retest#90] opened 2022-02-19 15:00 UTC
So I have a strange issue. I run retest in the docker container with the command
```
retest 'spring retest rspec <test>'
```
Running rspec with spring to speed up test initialization works fine.
Also, doing a save on any "*_spec.rb" file immediatelly reruns the spec. This is also fine.

However, when saving changes on an "*.rb" file, it takes about 5 seconds for the corresponding spec to run each time. Spring seems to work fine (spec starts executing, Spring reports it being preloaded, but only after the initial 5 seconds), so I was thinking - is it possible the file path to the spec file is not cached, and retest needs to search for the file each time we save?

Rails 6.1.3.2
Ruby 3.0.3

**Comment by VlatkoGoljevacki** [comment] 2022-02-20 11:10
Okay, some further findings. It seems this doesn't happen all the time. Some files (and their respective spec files) run immediately, while other files have a kind of delay before running

As an example, this takes a few seconds to start after saving:
```
decorator/spree/some_view.rb
```
saving the spec file starts tests immediatelly.

However, after saving:
```
/service/any_file_here.rb
```
The specs run instantaneously.

Another thing I've noticed, if there is no corresponding spec file, retest will instead start running specs from a filename with a similar name, instead of letting us know the spec file is missing.

**Comment by AlexB52** [comment] 2022-02-21 21:17
Hi @VlatkoGoljevacki 

Sorry for the late response, I found your issue by chance. Somehow I missed a notification from GitHub.
Thanks for raising an issue.

## Slow run

> Okay, some further findings. It seems this doesn't happen all the time. Some files (and their respective spec files) run immediately, while other files have a kind of delay before running

The behaviour seems to be difficult to reproduce but I did realise that sometime it's a bit slow too. Would you be able to capture a video/gif of the behaviour you're witnessing?

There are few leads I can think of:

* Maybe we don't cache the file properly. 
* Maybe the gem `listen` takes a longer time to identify a change. 
* Maybe it depends on how many ruby files we're watching. 

**Would you be able to count the number of `.rb` files you have on your repository, please?**

Something like this would work. In this example I've run this command on the retest repository. This command find all the files in the current directory, filter only the ruby files and count them
```bash
find . -type f | grep .rb | wc -l
225
```

## Rerun a test file when not found

> Another thing I've noticed, if there is no corresponding spec file, retest will instead start running specs from the previously cached file path, instead of letting us know the spec file is missing.

Currently this is a feature not a bug :joy: Here are the [running rules](https://github.com/AlexB52/retest#running-rules) 
_It will only run a 404 if there was no previous command run._

Initially retest used to listen to all file changes. This was done so that when changing any other files than a `.*rb` file (like .json or .yml) during a refactoring you would still be running the previous test and make sure you wouldn't break what you were refactoring. 

Since we only listen to `.rb` files now, I understand that the behaviour is confusing. I will look into this and see what would be a better behaviour when no tests is found :+1:

**Comment by AlexB52** [comment] 2022-02-21 22:02
I looked at the listen gem and there is a logger with a debug options. 

You could run and maybe find something relevant when the run starts to slow down? I'll try this as well when working.
```bash
LISTEN_GEM_DEBUGGING=debug retest 'spring rspec <test>'
```

**Comment by VlatkoGoljevacki** [comment] 2022-02-23 21:51
Hey @AlexB52 

There are 1454 .rb files in my repo. I'm also using the Spree e-commerce gem, which is famous for using "decorators", i.e. modules which are prepended to a named class to update/change its functionality.
A lot of this "slowness" appears when running tests on class that was decorated this way. I still have to check if this is the only time the problem appears.

When using the listen gem debugger, I get the following output. (Running with Spring "on" at both times)
Saving a "_spec.rb" file (instantaneous specs):
```
<file_name>
Running via Spring preloader in process 316
<this is where the specs start executing>
```
Saving the actual ".rb" file (delayed specs):
```
<file_name>
D, [2022-02-23T21:46:57.760332 #306] DEBUG -- : inotify: log/development.log ([:close_write, :close])
D, [2022-02-23T21:46:57.760434 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.385506 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.385587 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.386301 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.386343 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.390532 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.390604 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.391268 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.391316 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.393410 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.393497 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.394095 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.394150 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.395461 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.395521 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.395968 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.396022 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.397188 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.397246 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.397872 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.397921 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.398653 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.398713 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.399398 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.399458 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.399959 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.400004 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.400529 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.400582 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.401682 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.401734 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.402052 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.402094 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.403133 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.403185 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.403517 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.403867 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.404486 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.404537 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.405151 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.405190 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.405563 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.405604 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.406109 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.406145 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.406996 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.407032 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.407362 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.407398 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.408266 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.408303 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.408603 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.408635 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.409667 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.409719 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.410127 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.410174 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.410620 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.410675 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.411251 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.411304 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.412356 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.412406 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.412725 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.412766 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.413805 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.413870 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.414211 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.414342 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.415615 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.415685 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.415873 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.415930 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.416426 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.416476 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.417025 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.417074 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.418094 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.418178 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.418686 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.418741 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.419786 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.419845 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.420122 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.420170 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.421331 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.421386 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.421607 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.421657 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.421995 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.422041 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.422556 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.422605 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.423489 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.423543 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.423902 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.423963 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.424831 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.424883 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.425155 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.425203 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.426336 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.426392 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.426648 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.426697 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.427071 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.427123 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.427619 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.427668 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.428519 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.428573 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.428898 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.428946 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.429689 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.429740 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.430028 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.430080 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.430899 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.430950 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.431890 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.431958 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.432157 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.432200 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.432742 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.432795 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.433992 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.434097 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.434593 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:04.434653 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:04.477956 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.478076 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.482758 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.482815 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.485306 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.485412 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.487117 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.487204 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.487953 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.488022 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.489004 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.489048 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.489452 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.489526 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.490481 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.490536 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.491454 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.491529 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.492474 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.492529 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.492937 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.493006 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.494305 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.494380 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.495112 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.495183 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.496158 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.496200 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.496591 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.496662 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.497632 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.497683 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.498556 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.498616 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.499590 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.499651 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.500083 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.500140 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.501435 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.501534 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.502372 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.502443 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.503643 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.503723 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.504172 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.504235 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.505452 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.505523 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.506600 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.506681 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.507702 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.507762 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.508188 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.508248 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.509194 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.509262 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.510590 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.510654 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.511214 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.511266 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.511648 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.511699 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:04.512585 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:04.512635 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:05.737085 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:05.737164 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:05.880613 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:05.880686 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:05.881316 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:05.881371 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:05.887195 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:05.887267 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:05.888238 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:05.888303 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:05.925295 #306] DEBUG -- : inotify: tmp/cache/bootsnap/compile-cache/47/9cc722325028a3.tmp.M89rGG ([:create])
D, [2022-02-23T21:47:05.925378 #306] DEBUG -- : (silenced): "tmp/cache/bootsnap/compile-cache/47/9cc722325028a3.tmp.M89rGG"
D, [2022-02-23T21:47:05.925551 #306] DEBUG -- : inotify: tmp/cache/bootsnap/compile-cache/47/9cc722325028a3.tmp.M89rGG ([:attrib])
D, [2022-02-23T21:47:05.925590 #306] DEBUG -- : (silenced): "tmp/cache/bootsnap/compile-cache/47/9cc722325028a3.tmp.M89rGG"
D, [2022-02-23T21:47:05.925742 #306] DEBUG -- : inotify: tmp/cache/bootsnap/compile-cache/47/9cc722325028a3.tmp.M89rGG ([:modify])
D, [2022-02-23T21:47:05.925781 #306] DEBUG -- : (silenced): "tmp/cache/bootsnap/compile-cache/47/9cc722325028a3.tmp.M89rGG"
D, [2022-02-23T21:47:05.925921 #306] DEBUG -- : inotify: tmp/cache/bootsnap/compile-cache/47/9cc722325028a3.tmp.M89rGG ([:close_write, :close])
D, [2022-02-23T21:47:05.925956 #306] DEBUG -- : (silenced): "tmp/cache/bootsnap/compile-cache/47/9cc722325028a3.tmp.M89rGG"
D, [2022-02-23T21:47:05.926154 #306] DEBUG -- : inotify: tmp/cache/bootsnap/compile-cache/47/9cc722325028a3.tmp.M89rGG ([:moved_from, :move])
D, [2022-02-23T21:47:05.926215 #306] DEBUG -- : moved_from: file:/app/tmp/cache/bootsnap/compile-cache/47/9cc722325028a3.tmp.M89rGG ({:cookie=>111564, :change=>:moved_from})
D, [2022-02-23T21:47:05.928276 #306] DEBUG -- : inotify: tmp/cache/bootsnap/compile-cache/47/9cc722325028a3 ([:moved_to, :move])
D, [2022-02-23T21:47:05.928383 #306] DEBUG -- : moved_to: file:/app/tmp/cache/bootsnap/compile-cache/47/9cc722325028a3 ({:cookie=>111564, :change=>:moved_to})
D, [2022-02-23T21:47:05.928682 #306] DEBUG -- : inotify: tmp/cache/bootsnap/compile-cache/47/9cc722325028a3 ([:attrib])
D, [2022-02-23T21:47:05.928721 #306] DEBUG -- : (silenced): "tmp/cache/bootsnap/compile-cache/47/9cc722325028a3"
D, [2022-02-23T21:47:05.939136 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:05.939221 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:05.941564 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:05.941650 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:05.941886 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:05.941941 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:05.944936 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:05.944997 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:06.000090 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:06.000161 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:06.211801 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:06.211853 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:06.212332 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:06.212385 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:06.271346 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:06.271420 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:08.647886 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:08.647951 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:08.648672 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:08.648725 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:08.734059 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:08.734163 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:08.775300 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:08.775384 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:08.775940 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:08.775987 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:08.776617 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:08.776667 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:08.777196 #306] DEBUG -- : inotify: log/development.log ([:modify])
D, [2022-02-23T21:47:08.777257 #306] DEBUG -- : (silenced): "log/development.log"
D, [2022-02-23T21:47:08.855732 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:08.855829 #306] DEBUG -- : (silenced): "log/test.log"
D, [2022-02-23T21:47:08.856078 #306] DEBUG -- : inotify: log/test.log ([:modify])
D, [2022-02-23T21:47:08.856154 #306] DEBUG -- : (silenced): "log/test.log"
Running via Spring preloader in process 316
<this is where the specs start executing>
```
I think it's pretty obvious the Listen gem is doing something unexpected here. Important to note, this does not happen with all files, only some. Still searching for a pattern.

Here's a gif as well (withou the debug log). First save is "_spec.rb", second save is ".rb", third save is "_spec.rb" again.

![save spec - save file - save spec](https://user-images.githubusercontent.com/44490333/155414737-666096fe-9173-4e36-9c6d-237d9e096f1c.gif)

**Comment by VlatkoGoljevacki** [comment] 2022-02-23 21:57
@AlexB52 Ok I think I figured out the problem (if not the solution).

I looked into the "log/development.log" at what was happening and it seems the app is re-initializing (i.e. running Spring has no effect when saving the ".rb" file).

**Comment by AlexB52** [comment] 2022-02-23 22:53
I'm not entirely sure whether this is retest at play here. Looking at your gif if you see `Test File Selected: <file_path>` means that listen was triggered, the test file has been found and the command has been run. 

> I looked into the "log/development.log" at what was happening and it seems the app is re-initializing (i.e. running Spring has no effect when saving the ".rb" file). Only this time it's not outputting to STDOUT.

Would you say it takes the same amount of time to run your spec as if spring was not involved? 

I wonder if the use of prepend requires some reloading which would reset spring and reload the app. I've definitely experienced and read something similar about `extend` in the past in Ruby but can't reproduce it and can't find it anywhere online so that this with a grain of salt.

**Comment by VlatkoGoljevacki** [comment] 2022-02-23 23:10
@AlexB52 Hah, you're right, that reloads spring (it appears it's a partial reload). A full one takes about 18 seconds, and the new one 9-10 seconds.

**Comment by AlexB52** [comment] 2022-02-27 20:39
@VlatkoGoljevacki Sounds good, let me know how this goes :+1:

**Comment by AlexB52** [comment] 2022-04-03 03:12
I'll close this issue as I think this is an expected Spring behaviour and not related to Retest.

**Closed by AlexB52** 2022-04-03 03:12 UTC
